package main

import (
	"errors"
	"fmt"
	"log"

	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime/middleware"

	"ex01/server/restapi"
	"ex01/server/restapi/operations"
)

type CandyRequest struct {
	Money      int64  `json:"money"`
	CandyType  string `json:"candyType"`
	CandyCount int64  `json:"candyCount"`
}

type Candy struct {
	Name  string `json:"name"`
	Price int64  `json:"price"`
}

var candyPriceList = []Candy{
	{
		Name:  "CE",
		Price: 10,
	},
	{
		Name:  "AA",
		Price: 15,
	},
	{
		Name:  "NT",
		Price: 17,
	},
	{
		Name:  "DE",
		Price: 21,
	},
	{
		Name:  "YR",
		Price: 23,
	},
}

func main() {
	// Загрузка встроенной спецификации Swagger с помощью функции loads.Embedded()
	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	// Создание экземпляра API сервера CandyServerAPI на основе загруженной спецификации Swagger.
	// Затем создается экземпляр сервера NewServer с использованием созданного API.
	// Отложенный вызов server.Shutdown() гарантирует, что сервер будет корректно остановлен при выходе из функции main
	api := operations.NewCandyServerAPI(swaggerSpec)
	server := restapi.NewServer(api)
	defer server.Shutdown()

	server.Host = "127.0.0.1"
	server.Port = 3333

	// обработка request
	api.BuyCandyHandler = operations.BuyCandyHandlerFunc(
		func(params operations.BuyCandyParams) middleware.Responder {
			// request
			candyRequest := CandyRequest{
				Money:      *params.Order.Money,
				CandyType:  *params.Order.CandyType,
				CandyCount: *params.Order.CandyCount,
			}

			// responses:
			// response 400
			candyPL, err := GetCandyFromPL(candyRequest)
			if err != nil {
				return operations.NewBuyCandyBadRequest().WithPayload(
					&operations.BuyCandyBadRequestBody{Error: fmt.Sprintf("%s", err)})
			}

			change := candyRequest.Money - (candyPL.Price * candyRequest.CandyCount)

			// response 402
			if change < 0 {
				return operations.NewBuyCandyPaymentRequired().WithPayload(
					&operations.BuyCandyPaymentRequiredBody{Error: fmt.Sprintf("Incorrect input: You need %d more money!", -change)})
			}

			// response 201
			return operations.NewBuyCandyCreated().WithPayload(
				&operations.BuyCandyCreatedBody{
					Change: change,
					Thanks: fmt.Sprintf("Thank you!"),
				})
		})

	// Запуск сервера на обслуживание входящих запросов методом Serve()
	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}
}

func RequestValid(candyReq CandyRequest) error {
	success := false
	for _, c := range candyPriceList {
		if c.Name == candyReq.CandyType {
			success = true
			break
		}
	}
	if !success || candyReq.CandyCount < 0 || candyReq.Money < 0 {
		return errors.New("Incorrect input: some error in input data")
	}
	return nil
}

// Get candy from price list
func GetCandyFromPL(candyReq CandyRequest) (Candy, error) {
	var findCandy Candy
	if err := RequestValid(candyReq); err != nil {
		return Candy{}, err
	}
	for _, c := range candyPriceList {
		if c.Name == candyReq.CandyType {
			findCandy = c
			break
		}
	}
	return findCandy, nil
}

/*
// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"fmt"
	"log"
	"os"

	"github.com/go-openapi/loads"
	flag "github.com/spf13/pflag"

	"ex01/server/restapi"
	"ex01/server/restapi/operations"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	var server *restapi.Server // make sure init is called

	flag.Usage = func() {
		fmt.Fprint(os.Stderr, "Usage:\n")
		fmt.Fprint(os.Stderr, "  todo-list-server [OPTIONS]\n\n")

		title := "Simple To Do List API"
		fmt.Fprint(os.Stderr, title+"\n\n")
		desc := "This is a simple todo list API\nillustrating go-swagger codegen\ncapabilities.\n"
		if desc != "" {
			fmt.Fprintf(os.Stderr, desc+"\n\n")
		}
		fmt.Fprintln(os.Stderr, flag.CommandLine.FlagUsages())
	}
	// parse the CLI flags
	flag.Parse()

	api := operations.NewCandyServerAPI(swaggerSpec)
	// get server with flag values filled out
	server = restapi.NewServer(api)
	defer server.Shutdown()

	server.ConfigureAPI()
	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}
*/

// ./main "--tls-certificate" ../../../ca/minica/server/cert.pem "--tls-key" ../../../ca/minica/server/key.pem
// sudo ./main --tls-certificate ../../../ca/minica/server/cert.pem --tls-key ../../../ca/minica/server/key.pem

/*

// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"log"
	"os"

	"github.com/go-openapi/loads"
	flags "github.com/jessevdk/go-flags"

	"ex01/server/restapi"
	"ex01/server/restapi/operations"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	api := operations.NewCandyServerAPI(swaggerSpec)
	server := restapi.NewServer(api)
	defer server.Shutdown()

	parser := flags.NewParser(server, flags.Default)
	parser.ShortDescription = "Candy Server"
	parser.LongDescription = swaggerSpec.Spec().Info.Description
	server.ConfigureFlags()
	for _, optsGroup := range api.CommandLineOptionsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			log.Fatalln(err)
		}
	}

	if _, err := parser.Parse(); err != nil {
		code := 1
		if fe, ok := err.(*flags.Error); ok {
			if fe.Type == flags.ErrHelp {
				code = 0
			}
		}
		os.Exit(code)
	}

	server.ConfigureAPI()

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}
*/
